import type { PersistentDefinition } from './types'

/** Shared executable rules. Numeric text follows the checked-in card catalogue. */
export const implementedPersistent: PersistentDefinition[] = [
  { id: 'human-pupa', name: '人蛹标本', triggers: [{ event: 'roundEnd', effects: [{ type: 'pupaGrowth' }] }] },
  { id: 'hatching-sac', name: '孵化囊', triggers: [{ event: 'addSucceeded',
    condition: { filter: { race: 'swarm' }, minGroups: 2 },
    effects: [{ type: 'stats', target: { mode: 'all' }, quantity: 45 }] }] },
  { id: 'proliferating-frontal-lobe', name: '增生前额叶', triggers: [{ event: 'roundEnd',
    condition: { filter: { race: 'awakened' }, minGroups: 2 },
    effects: [{ type: 'stats', target: { mode: 'random', filter: { rarities: ['rare', 'boss'] } }, activity: 80 }] }] },
  { id: 'hypertrophic-pituitary', name: '肿大脑垂体', triggers: [{ event: 'roundEnd',
    condition: { filter: { race: 'awakened', rarities: ['rare', 'boss'] }, minGroups: 1 },
    effects: [{ type: 'stats', target: { mode: 'random' }, activity: 80 }] }] },
  { id: 'adhesive-metatarsal', name: '粘连跖骨', triggers: [{ event: 'removeSucceeded',
    condition: { filter: { race: 'construct' }, minGroups: 2 },
    effects: [{ type: 'stats', target: { mode: 'random' }, quantity: 180 }] }] },
  { id: 'contracted-claw', name: '挛缩指爪', triggers: [{ event: 'removeSucceeded', excludedEventRace: 'construct',
    effects: [{ type: 'stats', target: { mode: 'random' }, quantity: 150 }] }] },
  { id: 'aberrant-bud', name: '孽生肉芽', triggers: [{ event: 'mutationCompleted', eventRace: 'aberrant',
    effects: [{ type: 'stats', target: { mode: 'all' }, activity: 35 }] }] },
  { id: 'mottled-liver', name: '斑斓肝脏', triggers: [{ event: 'mutationCompleted',
    condition: { filter: { race: 'aberrant' }, minGroups: 2 },
    effects: [{ type: 'stats', target: { mode: 'all' }, activity: 20 }] }] },
  { id: 'clustered-insect-eggs', name: '簇生虫卵', triggers: [{ event: 'roundEnd',
    condition: { filter: { race: 'swarm' }, minGroups: 3 },
    effects: [{ type: 'add', count: 1, spec: { filter: { race: 'swarm' }, quantityBonus: 100 } }] }] },
  { id: 'molting-cortex', name: '蜕生脑皮层', triggers: [{ event: 'roundEnd',
    effects: [{ type: 'fuseMatching', count: 2, filter: { rarities: ['magic'] }, race: 'awakened', rarity: 'rare' }] }] },
  { id: 'beast-tendon-cord', name: '兽筋绞肉索', triggers: [{ event: 'roundEnd',
    condition: { filter: { race: 'construct' }, minGroups: 2 },
    effects: [{ type: 'devour', victim: { mode: 'lowest', filter: { excludeRace: 'construct' } },
      recipient: { mode: 'random', filter: { race: 'construct' } } }] }] },
  { id: 'writhing-spinal', name: '蠕动脊髓', triggers: [{ event: 'addSucceeded', effects: [
    { type: 'chance', probability: .75, effects: [
      { type: 'mutate', target: { mode: 'eventMonster' }, race: 'aberrant', activityBonus: 80 },
    ] },
  ] }] },
  { id: 'leather-restraint', name: '生皮革拘束带', triggers: [{ event: 'roundEnd',
    condition: { filter: { rarities: ['magic'] }, minGroups: 3 },
    effects: [{ type: 'stats', target: { mode: 'highest' }, quantity: 100 }] }] },
  { id: 'black-goat-suture', name: '黑山羊肠缝线', triggers: [{ event: 'roundEnd',
    effects: [{ type: 'fuseMatching', count: 3, filter: { rarities: ['common', 'magic', 'rare'] },
      sameRarity: true, upgradeSteps: 1, repeat: true }] }] },
  { id: 'iron-bone-saw', name: '生铁骨锯', triggers: [{ event: 'roundEnd',
    effects: [{ type: 'stats', target: { mode: 'all', filter: { minQuantityExclusive: 150, minActivityExclusive: 150 } },
      activity: 15, quantity: 15 }] }] },
  { id: 'two-inch-skull-nail', name: '二寸颅骨钉', triggers: [{ event: 'addFailedBoardFull',
    effects: [{ type: 'stats', target: { mode: 'lowest' }, activity: 25, quantity: 25 }] }] },
  { id: 'dirty-bone-scraper', name: '脏污刮骨刀', triggers: [{ event: 'roundEnd',
    effects: [{ type: 'stats', target: { mode: 'all', filter: { minQuantityExclusive: 275 } }, activity: 20 }] }] },
  { id: 'canine-rasp', name: '犬牙锉刀', triggers: [{ event: 'roundEnd',
    effects: [{ type: 'stats', target: { mode: 'all', filter: { minActivityExclusive: 255 } }, quantity: 30 }] }] },
  { id: 'plague-madonna', name: '疫区圣母像', triggers: [{ event: 'roundEnd', everyRounds: 2,
    effects: [{ type: 'upgradeEachRarity' }] }] },
  { id: 'alien-sting', name: '异形蛰针', triggers: [{ event: 'roundEnd', everyRounds: 3,
    effects: [{ type: 'randomizeAll' }] }] },
  { id: 'tanned-leather-restraint', name: '鞣制皮革拘束带', triggers: [{ event: 'roundEnd',
    condition: { filter: {}, minGroups: 3, all: ['common', 'magic', 'boss'].map(rarity => ({
      filter: { rarities: [rarity as 'common' | 'magic' | 'boss'] }, minGroups: 1,
    })) }, effects: [{ type: 'stats', target: { mode: 'all' }, activity: 20 }] }] },
  { id: 'eyelid-dilator', name: '眼睑扩张器', triggers: [{ event: 'removeSucceeded',
    effects: [{ type: 'stats', target: { mode: 'highest' }, activity: 20, quantity: 20 }] }] },
  { id: 'second-born-beak', name: '二度降生者之喙', triggers: [{ event: 'roundEnd', effects: [
    { type: 'add', count: 1, spec: {}, condition: { filter: {}, minGroups: 2, maxGroups: 2 } },
    { type: 'devour', victim: { mode: 'lowest' }, recipient: { mode: 'highest' },
      condition: { filter: {}, minGroups: 6, maxGroups: 6 } },
  ] }] },
  { id: 'nettle-loop', name: '荨麻绳扣', triggers: [{ event: 'roundEnd',
    condition: { filter: { rarities: ['common'] }, minGroups: 3 },
    effects: [{ type: 'stats', target: { mode: 'all' }, quantity: 30 }] }] },
]
